osx_image: xcode11.3
language: objective-c
branches:
  only:
    - develop
    - master
notifications:
  email: false
install:
  - gem install bundler
  - bundle install
script: bundle exec fastlane ios bonjour
script: curl -H "Content-Type: application/json" --request POST --data '{"content": "Un nouveau push a ee effectué sur master faites attention"}' https://discordapp.com/api/webhooks/671632564787871755/5aPaQIMq69HSSngzM1VQT5CPoT-DaPDAgvXmCMMbpsn7uHEjmDiucOUi08wSXhKQv3ia
