osx_image: xcode11.3
language: objective-c
before_install:
  - chmod +x curlDiscord.sh
  - chmod +x git.sh
branches:
  only:
    - tests
notifications:
  email: false
install:
  - gem install bundler
  - bundle install
script: 
  - ./curlDiscord.sh
  - ./git.sh
  - bundle exec fastlane ios unitTest