osx_image: xcode11.3
language: objective-c
before_install:
  - chmod +x curlDiscord.sh
branches:
  only:
    - master
notifications:
  email: false
install:
  - gem install bundler
  - bundle install

deploy:
  - provider: script
    script: bundle exec fastlane ios unitTest
    on:
      branch: master
   - provider: script
    script: ./curlDiscord.sh
    on:
      branch: gh-page
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: gh-page