osx_image: xcode11.3
language: objective-c
before_install:
  - chmod +x curlDiscord.sh
branches:
  only:
    - develop
    - master
notifications:
  email: false
install:
  - gem install bundler
  - bundle install
script: ./curlDiscord.sh