osx_image: xcode11.3
language: objective-c
before_install:
  - chmod +x curlDiscord.sh
  - chmod +x git.sh
branches:
  only:
    - master

notifications:
  email: false
install:
  - gem install bundler
  - bundle install
script: 
  - ./curlDiscord.sh
  - bundle exec fastlane ios unitTest
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
