# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "My best lane <3"
    lane :unitTest do
      get_version_number
      print git_branch
      increment_version_number(bump_type: "major")
      scan(code_coverage: true)
      upload_to_testflight(
        username: "arthurblanc98@gmail.com",
        app_identifier: "com.esgi.Test2020"
      )
      xcov
    end
end
